server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: DB
  application:
    name: order-service

client:
  inventory-service:
    baseUrl: http://localhost:8083/api/v1/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/