server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: DB
  application:
    name: inventory-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
